### ISSUE TITLE
ignore_* options do not appear to work when added to urlwatch.yaml

### ISSUE THREAD

**Issue by jpiszcz** [thp/urlwatch#462] opened 2020-03-11 17:56 UTC
Per the documentation, added the following parameters to $HOME/.config/urlwatch/urlwatch.yaml

    url:
          ignore_connection_errors: true
          ignore_http_error_codes: 4xx, 5xx

I still get connection errors.  When I add these two options beneath the URL that is failing with connection errors, I no longer get e-mails about it.

Version being used:
ii  urlwatch                             2.17-1                           all          monitors webpages for you

**Comment by cfbao** [comment] 2020-03-11 23:07
> When I add these two options beneath the URL that is failing with connection errors, I no longer get e-mails about it.

Isn't this the expected bahaviour?

Perhaps you can elaborate some more on what the issue is about? What are you trying to achieve, what did you do, what's the behaviour you want, and what's the behaviour observed, in details.

**Comment by jpiszcz** [comment] 2020-03-11 23:19
Hello,

 

When these two lines are added to the global urlwatch.yaml under the url: component, they do not produce their intended effect:

ignore_connection_errors: true

ignore_http_error_codes: 4xx, 5xx

 

However, when I add these two lines under each individual entry, it works properly and I do not get alerts if a website is off-line/timeout.   However, I need to add these for _every_ entry.

ignore_connection_errors: true

ignore_http_error_codes: 4xx, 5xx

 

Success Scenario: Example (successful outcome, no e-mail alerts when there are failures)

 

name: "Kernel Newbies Linux Changes"

url: "https://kernelnewbies.org/LinuxChanges"

ignore_connection_errors: true

ignore_http_error_codes: 4xx, 5xx

filter: html2text

---

name: "New Linux Kernel released!"

url: "https://www.kernel.org"

ignore_connection_errors: true

ignore_http_error_codes: 4xx, 5xx

filter: html2text,grep:5\.\d+$,strip

 

urlwatch.yaml (bottom of file snippet)

 

  job_defaults:

    all:

      timeout: 60

    url:

    headers:

 

Failure Scenario: Example (not successful, I get failures for connection issues every time if a website is offline)

 

name: "Kernel Newbies Linux Changes"

url: "https://kernelnewbies.org/LinuxChanges"

filter: html2text

---

name: "New Linux Kernel released!"

url: "https://www.kernel.org"

filter: html2text,grep:5\.\d+$,strip

 

 

urlwatch.yaml (bottom of file snippet)

 

  job_defaults:

    all:

      timeout: 60

    url:

      ignore_connection_errors: true

      ignore_http_error_codes: 4xx, 5xx

    headers:

 

Am I putting the global options in the wrong spot?

https://github.com/thp/urlwatch

 

The following does not appear to be working (ignore connection errors) when in global:

 

If you want to change some settings for all your jobs, edit the job_defaults section in your config file:

...

job_defaults:

  all:

    diff_tool: wdiff

  url:

    ignore_connection_errors: true

 

 

 

 

Regards,

 

Justin.

**Comment by cfbao** [comment] 2020-03-11 23:34
I see, but I cannot replicate your issue.
Can you check that there's no space before `job_defaults:` in your `urlwatch.yaml` file?

**Comment by jpiszcz** [comment] 2020-03-11 23:48
Hello,

 

That was it—it is working now!

 

Thanks!

 

Regards,

 

Justin.

**Comment by jprokos** [comment] 2020-03-12 17:21
While I am grateful for this project... it would be great if there were information on the exact formatting for the config file and jobs. In some cases the configuration option follows the colon with a space between, some cases there should be no space. And in some cases it should be on a new line and indented by three spaces, etc.  For "newbs" like me going through every permutation is time consuming. If I had ultimate urlwatch knowledge I would do this myself, but I am hardly "the one".

**Comment by cfbao** [comment] 2020-03-12 20:21
Urlwatch doesn't define the exact format. It uses YAML (as indicated by the file extension).

YAML is a standard and very widely used config file format. A lot of new users' config related questions can be addressed by learning a bit of YAML syntax.

**Comment by jprokos** [comment] 2020-03-12 20:32
Excellent! Thank you for this information.

**Closed** 2020-07-20 09:53 UTC
