### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by sbraz** [thp/urlwatch#140] opened 2017-03-17 11:08 UTC
Hi, I have two instances running at the same time and I sometimes get this error

```
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/urlwatch/handler.py", line 62, in process
    self.load()
  File "/usr/lib64/python3.5/site-packages/urlwatch/handler.py", line 54, in load
    self.old_data, self.timestamp = self.cache_storage.load(self.job, self.job.get_guid())
  File "/usr/lib64/python3.5/site-packages/urlwatch/storage.py", line 474, in load
    where=CacheEntry.c.guid == guid, limit=1):
  File "/usr/lib64/python3.5/site-packages/minidb.py", line 928, in query
    return db.query(cls, select=select, where=where, order_by=order_by, group_by=group_by, limit=limit)
  File "/usr/lib64/python3.5/site-packages/minidb.py", line 395, in query
    result = self._execute(sql, args)
  File "/usr/lib64/python3.5/site-packages/minidb.py", line 157, in _execute
    return self.db.execute(sql, args)
sqlite3.OperationalError: database is locked
```
It seems to be similar to https://github.com/thp/urlwatch/issues/66. I liked @brbsix's idea of adding a file-level lock.

**Comment by thp** [comment] 2017-10-01 08:49
Closing as duplicate of #66, let's handle both issues there.

**Closed by thp** 2017-10-01 08:49 UTC
