### ISSUE TITLE
Issue: cannot VACUUM from within a transaction

### ISSUE THREAD

**Issue by dinosaw** [thp/urlwatch#125] opened 2017-01-15 20:04 UTC
I'm running into an odd issue when running `urlwatch`. The `--config` and `--config-edit` works fine, however when I actually run the application, I get the following:

```
urlwatch 2.6, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 1 URLs in 1 seconds
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.0/bin/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlwatch/main.py", line 97, in close
    self.cache_storage.close()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/urlwatch/storage.py", line 465, in close
    self.db.close()
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/minidb.py", line 170, in close
    self._execute('VACUUM')
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/minidb.py", line 153, in _execute
    return self.db.execute(sql)
sqlite3.OperationalError: cannot VACUUM from within a transaction
```

```
root@server1:~# python --version
Python 3.6.0
root@server1:~# pip3 --version
pip 9.0.1 from /root/.pyenv/versions/3.6.0/lib/python3.6/site-packages (python 3.6)
```

Also just to verify, I made sure all dependencies were [installed/satisifed](http://pastebin.com/raw/3G8Ywdby).

Any help would be appreciated!

**Comment by thp** [comment] 2017-01-15 20:34
Duplicate of #123.

**Closed by thp** 2017-01-15 20:34 UTC
