### ISSUE TITLE
Atom feed reporter

### ISSUE THREAD

**Issue by fstirlitz** [thp/urlwatch#76] opened 2016-06-25 19:49 UTC
I'd love to have urlwatch output an Atom feed which I'd then be able to import into my feed reader.

Liferea supports reading feeds generated by a command-line program; it could work great together with urlwatch.

**Comment by thp** [comment] 2016-07-12 19:49
Closing as duplicate of https://github.com/thp/urlwatch/issues/76 -- whether we use RSS or Atom should just be an implementation detail, feed readers can usually handle both.

**Closed by thp** 2016-07-12 19:49 UTC
