### ISSUE TITLE
'navigate' does not render JS

### ISSUE THREAD

**Issue by andreiz** [thp/urlwatch#511] opened 2020-06-23 20:16 UTC
Using urlwatch 2.17. I configured a job:

```
name: "Sante Adairius"
kind: browser
navigate: https://www.rusticalesonline.com/
```

The page is created via a JSON payload embedded in the page that is rendered into HTML by Javascript. So I expected urlwatch to fetch the rendered version for comparison, but it keeps fetching the raw one, with JSON/JS. Am I doing something wrong?

**Comment by cfbao** [comment] 2020-06-23 20:20
This is a known issue #293.

Attempts to fix this: #355, #500

**Comment by thp** [comment] 2020-07-21 19:13
Marking as duplicate of #293. See there.

**Closed by thp** 2020-07-21 19:13 UTC
Labels: bug
