### ISSUE TITLE
Delivering HighPriority messages with Pushover

### ISSUE THREAD

**Issue by JsBergbau** [thp/urlwatch#346] opened 2019-01-13 16:20 UTC
How can I configure that the messages should be high priority? High priority messages can be configured that they are played by "Alarm" queue, so even if your smartphone is in silent mode you get an notification.

**Comment by 3mru** [comment] 2019-06-15 17:50
Did you ever figure it out?

**Comment by JsBergbau** [comment] 2019-06-23 13:23
I don't use the built-in notification services, but instead created my own. Thats much more flexible. In fact he build-in mail notification didn't work for me. There was some problem with keyring (I'd prefer just to store password in plaintext instead of this keyring thing, because if urlwatch can read the PW also other applications can get it out), so first I've used the stdout output and cron to mail the changes.

So here are the scripts for mailing and for pushover.

pushover.sh
```
#!/bin/bash

if [ $# -ne 1 ]
then
        echo "Usage: Arg1 ist die Nachricht"
        exit 1
fi

prio=$(<pushoverPrioritaet)

curl -s \
  --form-string "token=<yourtoken>" \
  --form-string "user=<yourusername>" \
  --form-string "message=$1" \
  --form-string "priority=$prio" \
  --form-string "title=Pushover Title" \
  --form-string "expire=30" \
  --form-string "retry=30" \
  --form-string "sound=siren" \
  https://api.pushover.net/1/messages.json
```

myurlwatch.sh 
```
#!/bin/bash

cd /home/pi/urlwatch

ausgabe=$(./urlwatch --urls <urls> --cache <yourcache>) #or just $(./urlwatch)

betreff=$(echo "$ausgabe" | grep -oP '(?<=^CHANGED: )[^(]*')
betreff=${betreff//[$'\t\r\n']}

if [ ${#ausgabe} -ge 3 ] #nur wenn mehr als 3 Zeichen (eine "neue Zeile ist immer enthalten)
then
	echo "$ausgabe" | mail --append "Content-Type: text/plain; charset=UTF-8" -s "$betreff" <yourmailadress@somewhere.com> #Mail delivery
       ./pushover.sh "$ausgabe" &> /dev/null
fi
```

**Comment by thp** [comment] 2020-07-10 13:37
This is implemented in #521, which makes this issue a duplicate of #408.

@JsBergbau Please give the code in #521 a try and report back if it fixes your issue.

**Closed by thp** 2020-07-10 13:37 UTC

**Comment by JsBergbau** [comment] 2020-07-12 06:57
Hi thp. Thanks for implementing. 
Just from code review it looks good, sorry I currently don't have the time to test it. 

Just a mention. Sometimes pushover fails to deliver messages, don't know why. thats why there is this backup code in the script above and I still get E-Mails in rare cases.

**Comment by thp** [comment] 2020-07-15 09:05
> Just from code review it looks good, sorry I currently don't have the time to test it.

Would be great if somebody could actually test it or provide me with a pushover test account, because code wise it also looks good to me, but if somebody could test and report "this actually worked with a notification", I'd feel more confident in merging :)

> Just a mention. Sometimes pushover fails to deliver messages, don't know why. thats why there is this backup code in the script above and I still get E-Mails in rare cases.

Probably the same reason as in #415 -- some (temporary) network or server issue with Pushover combined with urlwatch not retrying reports (but still storing the new page state). Not yet sure what the solution there is (but feel free to subscribe/comment in #415), maybe some kind of queue so that message sending is retried later.
