### ISSUE TITLE
[Feature request] Show updates as a rss feed

### ISSUE THREAD

**Issue by Clarin98** [thp/urlwatch#219] opened 2018-03-15 19:46 UTC
This is a very helpful app for my static-HTML5 web site, but I would like to have access to a generated rss feed. A few days ago I was thinking that urlwatch could be linked (through mail or telegram bot) to another app like  [feed2oomb](https://gitlab.com/CiaranG/feed2omb/) but for me (a very noob non-programmer but technology-interested person) it seems a little hard. Could urlwatch produce its own rss feed to see it in clients like QuiteRSS?

**Comment by thp** [comment] 2018-03-20 09:43
Duplicate of #53?

**Comment by thp** [comment] 2018-06-03 11:46
Duplicate of #53. :)

**Closed by thp** 2018-06-03 11:46 UTC
