### ISSUE TITLE
Debug of custom filters

### ISSUE THREAD

**Issue by ad-m** [thp/urlwatch#98] opened 2016-10-02 18:43 UTC
Hello,

I am would like ask about debug of filters. Is there any way to dry-run filters eg.
`urlwatch [URL] --filter="grep:X"` to debug filters without modify cache and swap to editor again and again?

Greetings,

**Comment by thp** [comment] 2016-10-02 18:50
Not yet, but sounds like a reasonable feature request. If anybody wants to implement that, I'd be happy to merge it.

**Comment by thp** [comment] 2017-10-01 08:44
Closing as duplicate of #69.

**Closed by thp** 2017-10-01 08:44 UTC
