### ISSUE TITLE
YAML Anchors/Aliases not working

### ISSUE THREAD

**Issue by Knuschberkeks** [thp/urlwatch#782] opened 2023-12-31 20:10 UTC
I'm not even sure if this is an issue with urlwatch or not, but:
I have a set of jobs that I need to apply the same set of filters to. So i tried this:
```
name: "test job 1"
url: "example.com"
filter: &testfilters
  - filter1
  - filter2
---
name:: "test job 2"
url: "example.net"
filter: *testfilters
```

but when I save I get the error `found undefined alias 'testfilters'`

**Comment by thp** [comment] 2024-01-01 20:13
Huh, I didn't even know those were a thing. We use `yaml.SafeLoader` (from PyYAML) for loading, can you try playing around with some other class in `lib/urlwatch/storage.py`?

**Comment by Knuschberkeks** [comment] 2024-01-03 09:12
I'm really sorry but I don't really understand what that means... I'm not really a programmer.

**Comment by Jamstah** [comment] 2024-01-17 14:04
This is actually because they are different yaml documents. YAML does not allow anchors/references between documents, even if they are in the same file.

See: https://yaml.org/spec/1.2-old/spec.html#id2800132

**Comment by thp** [comment] 2024-04-24 19:18
Closing this as "works as intended" for now.

**Closed by thp** 2024-04-24 19:18 UTC
