### ISSUE TITLE
Can we add sleep?

### ISSUE THREAD

**Issue by cattlehound** [thp/urlwatch#370] opened 2019-03-28 01:37 UTC
I've got a number of pages hosted on the same site, and I'm running up against "429 Client Error: Too Many Requests for url"

Can we add a delay via sleep. If so, where?

**Comment by thp** [comment] 2019-03-29 18:08
How often do you run urlwatch? Or do you mean that in a single run, you are running into this issue?

**Comment by cfbao** [comment] 2019-04-13 06:42
This seems similar to #331.

**Comment by thp** [comment] 2020-07-10 13:45
Yes, duplicate of #331.

**Closed by thp** 2020-07-10 13:45 UTC
