### ISSUE TITLE
SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])")))

### ISSUE THREAD

**Issue by foice** [thp/urlwatch#378] opened 2019-04-13 12:23 UTC
Any idea about
Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])")))

I have already tried the `ssl_no_verify: true` option.

**Comment by cfbao** [comment] 2019-04-13 15:01
Seems like a duplicate of #362.

**Comment by foice** [comment] 2019-04-13 16:08
maybe duplicate, although error is different. Indeed my attempt with
ssl_no_verify:
true from #265 did not work.
... and the external link ... I do not understand his point, should one
reinstall python configuring SSL in a different way at the ./configure
stage? or what?
https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/

**Comment by cfbao** [comment] 2019-04-13 17:30
There's nothing you can do for now. Changes in `urlwatch` are needed in order to loosen `requests`'s strict default requirements.

If you can tell us which site you were trying to monitor, it'd be a lot more helpful.

**Comment by RobertoFranceschini** [comment] 2019-07-01 21:45
I have tried to reinstall python (I have compiled from sources with SSL) and [here it is the link which still does not work](https://bandomontalcini.cineca.it/)

**Closed** 2020-07-10 12:58 UTC

**Comment by dipendrachaudhary** [comment] 2021-06-11 17:57
same error

**Comment by mborsetti** [comment] 2021-06-17 23:56
@dipendrachaudhary What URL is throwing that error?

**Comment by dipendrachaudhary** [comment] 2021-06-18 04:49
hi @mborsetti

facing this issue while connection to windows 2008
192.168.10.6 | UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='192.168.10.6', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])\")))",
    "unreachable": true
}
Inventory file
[win]
192.168.10.4
[win:vars]
ansible_user=Administrator
ansible_password="password"
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_kerberos_delegation=true

**Comment by mborsetti** [comment] 2021-06-18 05:25
@dipendrachaudhary  Ah, it's a private IP space so not publicly reproduceable.  Sorry, can't help.

The issue appears to be that the server is trying to establish a secure connection using an old, unsafe, protocol (e.g. SSLv2), one that is no longer supported (for obvious security reasons) by today's crypto tools. If you control the server, it's an 'easy' fix; (upgrade it!); if not, there's nothing that can be done since that protocol has been dropped.

In either case since Python uses the OpenSSL library you should be able to get a more in depth explanation of the error by running the [s_client](https://www.openssl.org/docs/man1.1.1/man1/s_client.html) command of the library from the OS, like this:
```
openssl s_client -connect 192.168.10.6:5986
```
